config/routes.rb
BuyNow::Application.routes.draw do
  resources :items
  
  post "cart_items/create", :controller => "cart_items", :action => "create",  :as => "add_to_cart"
  
  root :to => "items#index"
  
  delete "cart_items/:id", :controller => "cart_items", :action => "destroy",  :as => "delete_cart_item" 
  
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  
  has_many :cart_items
  
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  
  belongs_to :item
  belongs_to :cart

  # before_filter :set_cart
  
  after_create :increase_total
  after_destroy :decrease_total
  
  def increase_total
    cart.total ||=0
    cart.total += self.PurchasePrice
    cart.save
  end
  
  def decrease_total
    cart.total ||= 0
    cart.total -= self.PurchasePrice
    cart.save    
  end

  
end

app/models/item.rb
class Item < ActiveRecord::Base
  
  has_many :cart_items
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def set_cart
    if session[:exist]
      @cart = Cart.find(session[:exist])
    else
      @cart = Cart.create
      session[:exist] = @cart.id
    end
  end
 
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  
  before_filter :set_cart
  
 def create
  @cart_item = @cart.cart_items.build(item_id: params[:zebra])
  @cart_item.PurchasePrice = @cart_item.item.price
  @cart_item.save
  redirect_to root_url
  
 end 
 
 def destroy
   @cart_item = CartItem.find(params[:id])
   @cart_item.destroy
   redirect_to root_url
 end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  before_filter :set_cart
  
  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    @cart_items = @cart.cart_items.all
    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>My Cart</h1>

<% @cart_items.each do |cart_item| %>
<li><%= cart_item.item.name  %> <%= number_to_currency(cart_item.PurchasePrice, precision: 0) %> <%= link_to "Delete", delete_cart_item_url(cart_item), confirm: "Are you sure?", method: "delete" %> </li>
<% end %>

<%= @cart.total %>

<hr>

<h1>Items for Sale</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.name %></td>
    <td><%= number_to_currency(item.price, precision: 0) %></td>
    <!-- <td><%= link_to 'Show', item %></td>
       <td><%= link_to 'Edit', edit_item_path(item) %></td>
       <td><%= link_to 'Destroy', item, confirm: 'Are you sure?', method: :delete %></td> -->
    <td><%= link_to 'Add To Cart', add_to_cart_url(zebra: item.id), method: "post" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BuyNow</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>